blank_issues_enabled: false
contact_links:
  - name: Security disclosure process
    url: https://github.com/apple/container/security/advisories/new
    about: Please report security vulnerabilities here.